### ISSUE TITLE
Repo Roadmap

### ISSUE THREAD

**Issue by confused-Techie** [pulsar-edit/pulsar-chocolatey#4]
### Have you checked for existing feature requests?

- [X] Completed

### Summary

Unfortunately this repo has been slightly neglected. Apologies for that, but here's hopefully my contract to resolve this.

As chocolatey has now been 5 versions out of date, lets do everything we can to automate this repo, and ensure we can continuously and timely publish this package for Pulsar users. In my mind to do so, that means we should accomplish the following goals:

* [x] Test: We should add tests for this repo, so that we don't have to manually test everything. Especially when the test process is basically running a pre-determined set of commands and finding what the output is, this should (hopefully) be trivial to automate
* [x] Auto Publish: Would love a way to get this repo to be able to auto-publish to chocolatey, so that we don't have to manually manage it all the time, likely via a triggerable CI run
* [x] Auto Update: Would be super cool, if a task could run automatically (or be triggered) to update the version of Pulsar being installed

---

EDIT::

Now that we have:
* Successful testing on each PR 
* A way to automatically create a new drafted version PR just by creating an issue
* Hopefully a complete functioning script that can publish based on being triggered 

There's only a few last steps needed to tie this all together:
* Add a Chocolatey API key to the repo's secrets
* Add the new docs to the ReadMe to make the order of events clear
* A nice to have, would be adding text to the PR body that it will close whatever issue opened it
* Test!

### What benefits does this feature provide?

Ensures that our `chocolatey` package is as up to date as possible, as quickly as possible.

### Any alternatives?

Leave this repo unfortunately neglected, and/or require to much manual effort to manage what should be a readily repeatable process.

**Comment by confused-Techie** [comment]
As everything listed here is now complete, we can go ahead and close this issue
